### ISSUE TITLE
Conflict with backlinks2

### ISSUE THREAD

**Issue by POpus** [dokufreaks/plugin-pagelist#72]
When **backlinks2** is placed after pagelist on a page, it does not work. It lists the backlinks of the previous page. For example:

**Page1** link to Page2.
**Page2** with backlinks indicate Page1 is calling page. Also link to Page 3.
**Page3** with pagelist then backlinks which indicates Page1 is calling page (not Page2).

If the backlinks entry is placed before the pagelist entry it will indicate Page2 is calling page.

My Wiki has a backlinks2 entry at the bottom of each page. I just recently added the pagelist plugin to the Wiki and came across this behavior. Also, if I edit and save Page 3 it will show the correct backlink, until a navigate away and back to it.

**Release 2015-08-10a "Detritus"
Ubuntu 14.04 Server
PHP Version 5.5.9-1ubuntu4.14**

**Comment by LarsGit223** [comment]
This strange issue in my opinion is not caused by the pagelist plugin.

I observed the following:
Setup:
As you described. I put the pages in a separate namespace called ```backlinks```. I also added 3 more pages 4,5, and 6. That pages only have a text in it (_"This is page x"_). No links, no call to the backlinks plugin.

Case 1 (**Not OK**):
If I create a pagelist including page 1,2 and 3 I see wrong backlinks list. Sometimes the backlinks lists even seems to change if I navigate through the pages and come back to page 3.

Case 2 (**OK**):
If I create a pagelist including page 4,5 and 6 I see a correct backlinks list. I can navigate through the pages and come back to page 3, everything seems to be fine all the time.

I am not sure if this is exactly your situation. But I assume the backlinks plugin has got problems if a page is linking to the other and vice versa. And this happens in Case 1 because the pagelist is also generating links to each page.

**Comment by LarsGit223** [comment]
I did some more testing:
I also get the problem if I include 3 simple internal links manually on page 3 pointing to page 1,2 and 3. This has to do with the links itself, not with the pagelist plugin.

Also I noticed the following:
- The problem does not occur if I use the page name e.g. ```{{backlinks>namespace:page3}}``` instead of the current page syntax ```{{backlinks>.}}```
- The problem disappears if I once clear the cahe by adding ```&Purge=true``` to the page3 address. Then it does not come back until I change page 3, save it and e.g. navigate from page 1 to 2 to 3.

Strange.

**Comment by Klap-in** [comment]
I cannot yet reproduce this. 
I guess https://github.com/mprins/dokuwiki-plugin-backlinks/pull/23 has already improve this, at least in the case mentioned in last post  `not occur if ..{{backlinks>namespace:page3}} instead of the current page syntax {{backlinks>.}}`
